### ISSUE TITLE
can't publish with [streamname]

### ISSUE THREAD

**Issue by uglyer** [langsim/liveserver#1]
Use OBS studio publish with [streamname](eg:rtmp://127.0.0.1/live/test)
tip connect error.
but without streamname it's run.

**Comment by langsim** [comment]
不要带中括号，中括号的意思是里面变量可以替换成其他变量。

**Comment by uglyer** [comment]
谢谢，但是并没有带中括号……
譬如 rtmp://192.168.1.2/live/test
用OBS 提示是失败的。

然后还有hls的切片大小是否能够设置？

**Comment by langsim** [comment]
这个地址的规则没有问题，注意有没有通过防火墙，如果obs用相同设置可以推到其他流媒体server上，也应该可以推到这个server上。

**Comment by uglyer** [comment]
我直接推到rtmp://192.168.1.2/live/ 是可行的。
只要后面添加了就不行。

**Comment by langsim** [comment]
印象里obs推流是分两段设置推流地址的，其中一个位置就应该填这个，另一个地方填流名

**Comment by uglyer** [comment]
谢谢，这样可以了，有办法能降低hls的延迟吗？
